version: '3.9'
services:
    ai:
        restart: always
        ports:
            - 8081:8080

    database:
        restart: always

    unstructured:
        restart: always

    minio:
        restart: always
