version: '3.9'
services:
    ai:
        build: ai
        volumes:
            - ./ai:/app
        environment:
            - LOCAL=1
            - PORT=8080
            - LIFF_CLIENT_ID=${LIFF_CLIENT_ID}
            - UNSTRUCTURED_ENDPOINT=http://unstructured:8000
            - SUPPORT_TYPES=application/pdf,text/html,text/markdown
            - S3_ENDPOINT=${S3_ENDPOINT}
            - S3_ACCESS_KEY=${S3_ACCESS_KEY}
            - S3_SECRET_KEY=${S3_SECRET_KEY}
            - S3_REGION=${S3_REGION}
            - OPENAI_KEY=${OPENAI_KEY}
        ports:
            - 8081:8080
        command: "sh -c 'sleep infinity'"

    database:
        image: 'ankane/pgvector'
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: line-ai-demo

    unstructured:
        image: quay.io/unstructured-io/unstructured-api:0.0.43

    minio:
        image: quay.io/minio/minio
        volumes:
            - ./blob-data:/data
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: password
        command: server /data --console-address ":9090"
